# Generated by Django 3.2.5 on 2021-07-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
