# Generated by Django 3.2.5 on 2021-07-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'permissions': (('can_publish_articles', 'Publish articles'),)},
        ),
    ]
