# Generated by Django 3.2.5 on 2021-07-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
