# Generated by Django 3.2.5 on 2021-07-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
